[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "micromodels"
authors = [{name = "Andrew Lee", email = "ajyl@umich.edu"}]
dynamic = ["version", "description"]
